name: Manual Admin Only Workflow

on:
  workflow_dispatch:

jobs:
  admin-check:
    runs-on: ubuntu-latest
    steps:
      run: |
          echo "Current Actor: ${{ github.actor }}"
          echo "Admin Permission: ${{ github.event.sender.permissions.admin }}"

  admin-task1:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.permissions.admin == true }}
    
    steps:
      - name: Run Admin Task
        run: echo "Hello Admin, you are authorized."

  admin-task2:
    runs-on: ubuntu-latest
    if: github.event.sender.permissions.admin == true
    
    steps:
      - name: Run Admin Task
        run: echo "Hello Admin, you are authorized."